modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/ClassicFood/issues"
license="MIT"

[[mods]]
modId="classicfood"
version="${file.jarVersion}"
displayName="Classic Food"
displayURL="https://www.curseforge.com/minecraft/mc-mods/classic-food"
authors="Mrbysco, ShyNieke"
description='''
Reimplements the old food to health system
'''
[[dependencies.classicfood]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.classicfood]]
modId="neoforge"
mandatory=true
versionRange="[20.2.59-beta,)"
ordering="NONE"
[[mixins]]
config = "classicfood.mixins.json"