modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Mrbysco/ClassicFood/issues"
license="MIT"

[[mods]]
modId="classicfood"
version="${file.jarVersion}"
displayName="Classic Food"
displayURL="https://www.curseforge.com/minecraft/mc-mods/classic-food"
authors="Mrbysco, ShyNieke"
description='''
Reimplements the old food to health system
'''
[[dependencies.classicfood]]
modId="minecraft"
mandatory=true
versionRange="[1.17,1.18)"
ordering="NONE"
side="BOTH"