modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/ClassicFood/issues"
license="MIT"

[[mods]]
modId="classicfood"
version="${file.jarVersion}"
displayName="Classic Food"
displayURL="https://www.curseforge.com/minecraft/mc-mods/classic-food"
authors="Mrbysco, ShyNieke"
description='''
Reimplements the old food to health system
'''
[[dependencies.classicfood]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21.6,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.classicfood]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.6.0-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="classicfood.mixins.json"